[2025-09-23T20:55:06.590+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-09-23T20:55:06.611+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wine_pipeline.stage2_train_model scheduled__2025-09-23T20:50:00+00:00 [queued]>
[2025-09-23T20:55:06.620+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wine_pipeline.stage2_train_model scheduled__2025-09-23T20:50:00+00:00 [queued]>
[2025-09-23T20:55:06.620+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-09-23T20:55:06.634+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): stage2_train_model> on 2025-09-23 20:50:00+00:00
[2025-09-23T20:55:06.641+0000] {standard_task_runner.py:72} INFO - Started process 815 to run task
[2025-09-23T20:55:06.645+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'wine_pipeline', 'stage2_train_model', 'scheduled__2025-09-23T20:50:00+00:00', '--job-id', '253', '--raw', '--subdir', 'DAGS_FOLDER/wine_pipeline.py', '--cfg-path', '/tmp/tmpxq8qcl1s']
[2025-09-23T20:55:06.648+0000] {standard_task_runner.py:105} INFO - Job 253: Subtask stage2_train_model
[2025-09-23T20:55:06.717+0000] {task_command.py:467} INFO - Running <TaskInstance: wine_pipeline.stage2_train_model scheduled__2025-09-23T20:50:00+00:00 [running]> on host a72da1fa20c9
[2025-09-23T20:55:06.826+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='wine_pipeline' AIRFLOW_CTX_TASK_ID='stage2_train_model' AIRFLOW_CTX_EXECUTION_DATE='2025-09-23T20:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-23T20:50:00+00:00'
[2025-09-23T20:55:06.828+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-09-23T20:55:16.786+0000] {local_task_job_runner.py:127} ERROR - Received SIGTERM. Terminating subprocesses
[2025-09-23T20:55:16.803+0000] {process_utils.py:132} INFO - Sending 15 to group 815. PIDs of all processes in the group: [817, 840, 841, 842, 843, 844, 845, 846, 847, 848, 849, 815]
[2025-09-23T20:55:16.806+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 815
[2025-09-23T20:55:16.821+0000] {taskinstance.py:3092} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-09-23T20:55:16.928+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/standard/operators/python.py", line 216, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/standard/operators/python.py", line 239, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/wine_pipeline.py", line 32, in run_training
    subprocess.run(["python", TRAIN_SCRIPT], check=True)
  File "/usr/local/lib/python3.11/subprocess.py", line 550, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/subprocess.py", line 1201, in communicate
    self.wait()
  File "/usr/local/lib/python3.11/subprocess.py", line 1264, in wait
    return self._wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/subprocess.py", line 2053, in _wait
    (pid, sts) = self._try_wait(0)
                 ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/subprocess.py", line 2011, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3094, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2025-09-23T20:55:16.934+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=842, status='terminated', started='20:55:09') (842) terminated with exit code None
[2025-09-23T20:55:16.938+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=849, status='terminated', started='20:55:09') (849) terminated with exit code None
[2025-09-23T20:55:16.940+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=wine_pipeline, task_id=stage2_train_model, run_id=scheduled__2025-09-23T20:50:00+00:00, execution_date=20250923T205000, start_date=20250923T205506, end_date=20250923T205516
[2025-09-23T20:55:16.984+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-09-23T20:55:17.045+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=815, status='terminated', exitcode=2, started='20:55:05') (815) terminated with exit code 2
[2025-09-23T20:55:17.047+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=840, status='terminated', started='20:55:09') (840) terminated with exit code None
[2025-09-23T20:55:17.048+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=843, status='terminated', started='20:55:09') (843) terminated with exit code None
[2025-09-23T20:55:17.050+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=847, status='terminated', started='20:55:09') (847) terminated with exit code None
[2025-09-23T20:55:17.051+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=848, status='terminated', started='20:55:09') (848) terminated with exit code None
[2025-09-23T20:55:17.053+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=844, status='terminated', started='20:55:09') (844) terminated with exit code None
[2025-09-23T20:55:17.054+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=845, status='terminated', started='20:55:09') (845) terminated with exit code None
[2025-09-23T20:55:17.055+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=817, status='terminated', started='20:55:06') (817) terminated with exit code None
[2025-09-23T20:55:17.056+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=846, status='terminated', started='20:55:09') (846) terminated with exit code None
[2025-09-23T20:55:17.057+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=841, status='terminated', started='20:55:09') (841) terminated with exit code None
[2025-09-23T20:55:17.058+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 143
[2025-09-23T20:55:17.109+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-23T20:55:17.144+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
